### ISSUE TITLE
fzf-exec-history escapes commands

### ISSUE THREAD

**Issue by popstas** [ytet5uy4/fzf-widgets#10]
For example, if I select command `git add --`, I got `git\ add\ --\`

**Comment by popstas** [comment]
Why you rewrited this widget? When I add https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh in `widgets` directory, history widget works fine: don't execute command after select, start search for substring if I pressed `Ctrl+R` on non-empty prompt, history updates immediately.

**Comment by ytet5uy4** [comment]
I used to use [anyframe](https://github.com/mollifier/anyframe) before.
I feeled dissatisfaction to `anyframe`, so I develop this plugin.

However I feeled official keybindings is very useful!
Therefore I will remove this widgit.
Thank you for the information!
