### ISSUE TITLE
fzf-git-checkout: git checkout -- test: pathspec 'test' did not match any file(s) known to git

### ISSUE THREAD

**Issue by popstas** [ytet5uy4/fzf-widgets#14]
## Environment

* `zsh --version`: 5.3.1

I trying to checkout to `test` branch.

## Actual behaviour
After widget select I expect:
```
git checkout test
```

## Expected behaviour
```
git checkout -- test
```

**Comment by ytet5uy4** [comment]
@popstas 
Thank you for report!
I fixed it.
