### ISSUE TITLE
Expansion of ~ isn't happening for cache directory

### ISSUE THREAD

**Issue by russell** [ytet5uy4/fzf-widgets#28]
Looks like the expansion of ~ when setting the default cache directory isn't happening correctly

```
russell at sparky in ~/projects/dotfiles on master
± find \~
~
~/.cache
~/.cache/fzf-widgets

russell at sparky in ~/projects/dotfiles on master
± export FZF_WIDGET_CACHE="${XDG_CACHE_HOME:-~/.cache}/fzf-widgets"

russell at sparky in ~/projects/dotfiles on master
± echo $FZF_WIDGET_CACHE
~/.cache/fzf-widgets
```
I think perhaps using $HOME might be a better option.

**Comment by popstas** [comment]
Have same behavior on macos: sometimes fzf-widgets creates directory `~` in current working directory, about month.

**Comment by ytet5uy4** [comment]
@russell @popstas
Thank you for report!
I fixed it.
