### ISSUE TITLE
Paste from fzf history don't replace command but append

### ISSUE THREAD

**Issue by popstas** [ytet5uy4/fzf-widgets#32]
## Environment

* `zsh --version`: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

* `uname -a`: Linux popstas-server 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* `fzf --version`: 0.16.11 (ecb6b23)

* antigen, oh-my-zsh

When I begin input command and complete it with ctrl+R:
df<ctrl+R><enter>

## Actual behaviour
`dfdf -h` (append to input)

## Expected behaviour
`df -h` (replace input)

Unfortunally, this bug appears about 4-5 months ago, but I forgot to tell about this. Please tell if you cannot reproduce this.

**Comment by popstas** [comment]
![upafilasas](https://user-images.githubusercontent.com/3027126/32901287-4fabaf6c-cb11-11e7-9c54-d2a1c1f4e279.gif)

**Comment by popstas** [comment]
I did checkouts po past commits and found that this bug was introduced in f854f2e (Refactor).

**Comment by ytet5uy4** [comment]
@popstas
Thank you as always.
I fixed this bug at https://github.com/ytet5uy4/fzf-widgets/pull/33.
Please try again after update.

**Comment by popstas** [comment]
Thank you! Now this leaves autosuggestion from https://github.com/zsh-users/zsh-autosuggestions, but it not matters.
