### ISSUE TITLE
CTRL + R is no longer working in zsh

### ISSUE THREAD

**Issue by emarcelcom** [ytet5uy4/fzf-widgets#36]
## Environment

* `zsh --version`: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
* `uname -a`: Linux saturn 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Actual behaviour
^R is throwing empty line "above" prompt

## Expected behaviour
^R shows history prompt

**Comment by ytet5uy4** [comment]
@emarcelcom
I tried zsh version you used, but didn't reproduce this issue.
Please show me a minimal .zshrc reproducing this issue.
Also show me screenshots or screencast to help explain this issue.

**Comment by emarcelcom** [comment]
here is URL  to screencast: 
https://www.dropbox.com/s/lkz7otkgupv2o2w/Nov-03-2018_13%3A03%3A49pm.mkv?dl=0

here is URL to zshrc: https://www.dropbox.com/s/bbz4oly9kpxrwkp/zshrc?dl=0

Basically when I hit ctrl + R nothing happens anymore. In bash it works as expected.

**Comment by popstas** [comment]
I have 5.4.2 too, Ubuntu 18.04 with updated packages, kernel 4.15.0-36-generic, Ctrl+R works.

**Comment by ytet5uy4** [comment]
@emarcelcom 
I saw your .zshrc, But you dotn't install `fzf-widgets`.
This issue has nothing to do with `fzf-widgets`, so I close this issue.

P.S. I recommend you create a **minimal** .zshrc removing all unnecessary parts to resolve this problem :smile:

**Comment by emarcelcom** [comment]
Here is how I fixed it:
Deleted /home/user/.zplug folder, run terminal, all widgets have been installed again and now all is  working as expected. Thanks! 

Cheers!!
