### ISSUE TITLE
fzf-git-add don't execute git add after select

### ISSUE THREAD

**Issue by popstas** [ytet5uy4/fzf-widgets#9]
When I select files and press Enter, i see `git add --` in command line.
![demo](http://g.recordit.co/5HXIBc57Vm.gif)

Plugin load with antigen, theme bira, other plugins disabled, macOS.

```
git add $(git status --porcelain | grep "^.[MD?]" | cut -c 4- | fzf -m)
```
works fine.

git 2.12.0
zsh 5.3.1

**Comment by popstas** [comment]
Sorry, it depends of my fix of #8, if I comment
```
selector-filter "awk '{print \$2}'"
```
widget executes correct.

**Comment by ytet5uy4** [comment]
Thank you for report!
However I want to view short format and relative path, so I fixed in a different way.
Please try again after update. :bowing_man:

**Comment by popstas** [comment]
Now it work fine!
